# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jsilva-r <jsilva-r@student.42porto.com>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/08/06 09:39:18 by jsilva-r          #+#    #+#              #
#    Updated: 2026/08/06 09:47:19 by jsilva-r         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=push_swap

SRCS= libft/ft_strlen.c src/algorithms/medium_2.c src/algorithms/medium.c src/algorithms/simple.c src/ops_stack/disorder.c src/ops_stack/free.c src/ops_stack/push.c src/ops_stack/reverse_rotate.c
src/ops_stack/rotate.c src/ops_stack/stack_create.c src/ops_stack/stack.c src/ops_stack/swap.c src/parsing/error.c src/parsing/parse.c src/parsing/parser.c src/utils/parser_utils.c
src/utils/stack_utils.c main.c

FLAGS=-Wall -Wextra -Werror

OBJS = $(SRCS:.c=.o)
%.o: %.c
	cc -c $(FLAGS) $?

all: $(NAME)

$(NAME): $(OBJS)
	ar rc $(NAME) $(OBJS)

clean:
	rm -rf $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re